import os
import json
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI(
    base_url="https://integrate.api.nvidia.com/v1",
    api_key=os.getenv("NVIDIA_API_KEY")
)

MODEL = "meta/llama-3.1-8b-instruct"

USER_DATA_FILE = "user_profile.json"
BASE_RESUME_PATH = "resumes/base.tex"


# ─────────────────────────────────────────────────────────
# STORAGE HELPERS
# ─────────────────────────────────────────────────────────

def save_user_data(data: dict):
    with open(USER_DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def load_user_data() -> dict:
    if os.path.exists(USER_DATA_FILE):
        with open(USER_DATA_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def load_base_resume() -> str:
    if os.path.exists(BASE_RESUME_PATH):
        with open(BASE_RESUME_PATH, "r", encoding="utf-8") as f:
            return f.read()
    return ""


# ─────────────────────────────────────────────────────────
# CORE LLM CALL (streaming)
# ─────────────────────────────────────────────────────────

def call_llm(system_prompt: str, user_prompt: str, temperature: float = 0.3) -> str:
    completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=temperature,
        top_p=0.95,
        max_tokens=16384,
        stream=True
    )
    full_response = ""
    for chunk in completion:
        if not chunk.choices:
            continue
        if chunk.choices[0].delta.content is not None:
            full_response += chunk.choices[0].delta.content
    return full_response


def clean_latex(text: str) -> str:
    """Strip markdown code fences if the model wraps output in them."""
    if "```latex" in text:
        text = text.split("```latex")[1].split("```")[0].strip()
    elif "```" in text:
        text = text.split("```")[1].split("```")[0].strip()
    return text.strip()


# ─────────────────────────────────────────────────────────
# THE FIXED PREAMBLE — never changes across any resume
# ─────────────────────────────────────────────────────────

LATEX_PREAMBLE = r"""\documentclass[letterpaper,10pt]{article}

%-------- ESSENTIAL PACKAGES ONLY (ATS-safe) --------
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage[usenames,dvipsnames]{color}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[english]{babel}
\usepackage{tabularx}
\usepackage{xcolor}
\usepackage{CormorantGaramond}
\usepackage{charter}
\input{glyphtounicode}
\pdfgentounicode=1

%-------- COLORS --------
\definecolor{airforceblue}{rgb}{0.36, 0.54, 0.66}
\definecolor{headingblue}{HTML}{0E5484}

%-------- MARGINS --------
\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1.19in}
\addtolength{\topmargin}{-.75in}
\addtolength{\textheight}{1.6in}
\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

%-------- SECTION FORMATTING --------
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large\bfseries\color{headingblue}
}{}{0em}{}[\color{airforceblue}\titlerule\vspace{-5pt}]

%-------- CUSTOM COMMANDS --------
\newcommand{\resumeItem}[1]{
  \item\small{#1\vspace{-2pt}}
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{1.0\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{\normalsize #1} & \textbf{\small #2} \\
      \textit{\small #3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-6pt}
}

\renewcommand\labelitemi{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.0in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}[leftmargin=0.15in]}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-4pt}}

%============================================================
\begin{document}"""

LATEX_END = r"\end{document}"


# ─────────────────────────────────────────────────────────
# AGENT 1 — BASE RESUME BUILDER
# User form data → body content → assembled into fixed template
# ─────────────────────────────────────────────────────────

def agent_build_base_resume(user_data: dict) -> dict:
    """
    Generates a complete LaTeX resume by:
    1. Asking the LLM to produce only the BODY content
    2. Prepending the fixed preamble and appending \end{document}
    The preamble, colors, and commands are never generated by the LLM.
    """

    # ── Format inputs for the prompt ──
    exp_text = ""
    for i, ex in enumerate(user_data.get("experience", [])):
        bullets = "\n".join([f"  - {b}" for b in ex.get("bullets", [])])
        exp_text += f"""
Position {i+1}:
  Title    : {ex.get('title', '')}
  Company  : {ex.get('company', '')}
  Duration : {ex.get('duration', '')}
  Location : {ex.get('location', '')}
  Bullets  :
{bullets}
"""

    edu_text = ""
    for i, ed in enumerate(user_data.get("education", [])):
        edu_text += f"""
Degree {i+1}:
  Degree     : {ed.get('degree', '')}
  University : {ed.get('university', '')}
  Year       : {ed.get('grad_year', '')}
  CGPA       : {ed.get('cgpa', '')}
"""

    proj_text = ""
    for i, pr in enumerate(user_data.get("projects", [])):
        descs = "\n".join([f"  - {d}" for d in pr.get("description", [])])
        proj_text += f"""
Project {i+1}:
  Name : {pr.get('name', '')}
  Tech : {pr.get('tech', '')}
  URL  : {pr.get('url', '')}
  Year : {pr.get('year', '')}
  Desc :
{descs}
"""

    system_prompt = r"""You are an expert LaTeX resume writer.

Your job is to generate ONLY the BODY of a LaTeX resume — the content that goes between \begin{document} and \end{document}.

The preamble (documentclass, packages, colors, custom commands) is already fixed and will be automatically added. Do NOT output \documentclass, \usepackage, \definecolor, \newcommand, \begin{document}, or \end{document}.

════════════════════════════════════════════════
AVAILABLE COMMANDS (already defined — use only these)
════════════════════════════════════════════════
\resumeSubHeadingListStart     — opens experience / education list
\resumeSubHeadingListEnd       — closes it
\resumeSubheading{A}{B}{C}{D} — one entry: A=Company/Degree, B=Date, C=Title/Program, D=Location
\resumeItemListStart           — opens bullet list under a job
\resumeItemListEnd             — closes bullet list
\resumeItem{text}             — one bullet point
\section{Name}                — blue section heading with rule

Available colors: \color{airforceblue}  \color{headingblue}

════════════════════════════════════════════════
SECTION ORDER (fixed — always output in this order)
════════════════════════════════════════════════
1. HEADER
2. \section{Summary}
3. \section{Technical Skills}
4. \section{Work Experience}
5. \section{Projects}
6. \section{Education}
7. \section{Certifications}   ← skip only if zero certifications provided

════════════════════════════════════════════════
EXACT FORMAT FOR EACH SECTION
════════════════════════════════════════════════

── HEADER ──
\begin{center}
  {\huge\textbf{FULL NAME}}\\[4pt]
  {\large\color{airforceblue}\textbf{TARGET JOB TITLE}}\\[5pt]
  \small
  PHONE ~\textbar~ \href{mailto:EMAIL}{EMAIL} ~\textbar~ \href{LINKEDIN}{linkedin.com/in/handle} ~\textbar~ \href{GITHUB}{github.com/handle}
\end{center}
\vspace{-10pt}

── SUMMARY ──
\section{Summary}
\begin{itemize}[leftmargin=0in, label={}]
  \item\normalsize{2-3 sentence summary. Bold 3-5 key technical terms with \textbf{}.}
\end{itemize}
\vspace{-14pt}

── TECHNICAL SKILLS ──
\section{Technical Skills}
\begin{itemize}[leftmargin=0in, label={}]
  \small\item{
    \textbf{Languages \& Databases:} Python, SQL ... \\[1pt]
    \textbf{BI \& Analytics Tools:} Power BI, Tableau ... \\[1pt]
    \textbf{Core Competencies:} ETL, Machine Learning ...
  }
\end{itemize}
\vspace{-14pt}

── WORK EXPERIENCE ──
\section{Work Experience}
\resumeSubHeadingListStart
  \resumeSubheading{Company Name}{Start -- End}{Job Title}{City, Country}
  \resumeItemListStart
    \resumeItem{Strong action-verb bullet. Bold \textbf{key metric or tech}.}
    \resumeItem{Another achievement with numbers where possible.}
  \resumeItemListEnd
\resumeSubHeadingListEnd
\vspace{-14pt}

── PROJECTS ──
\section{Projects}
\resumeItemListStart
  \resumeItem{\textbf{Project Name} --- description with \textbf{bold key tech/results}. \href{URL}{\color{headingblue}\underline{GitHub}}}
  \vspace{-4pt}
\resumeItemListEnd
\vspace{-14pt}

── EDUCATION ──
\section{Education}
\resumeSubHeadingListStart
  \resumeSubheading{Degree --- Field of Study}{Year}{University Name, City}{}
\resumeSubHeadingListEnd
\vspace{-14pt}

── CERTIFICATIONS ──
\section{Certifications}
\begin{itemize}[leftmargin=0in, label={}]
  \item\normalsize{\textbf{Certificate Name} --- Issuer (Year): one-line description.}
\end{itemize}

════════════════════════════════════════════════
WRITING RULES
════════════════════════════════════════════════
- If summary is blank → auto-generate a strong 2-3 sentence summary from the profile data
- Start every bullet with a strong past-tense action verb
- Use numbers/metrics wherever possible: "40% reduction", "2M+ records", "5 dashboards"
- Bold 3-5 key technical terms per section with \textbf{}
- Escape all special LaTeX characters: & → \&   % → \%   $ → \$   # → \#   _ → \_
- Omit \href if URL field is empty
- Output ONLY LaTeX body content — no preamble, no \begin{document}, no \end{document}
"""

    user_prompt = f"""Generate the LaTeX resume body content for:

NAME         : {user_data.get('full_name', '')}
EMAIL        : {user_data.get('email', '')}
PHONE        : {user_data.get('phone', '')}
LOCATION     : {user_data.get('location', '')}
LINKEDIN     : {user_data.get('linkedin', '')}
GITHUB       : {user_data.get('github', '')}
JOB TITLE    : {user_data.get('job_title', '')}
SUMMARY      : {user_data.get('summary', '(auto-generate)')}

TECH SKILLS  : {', '.join(user_data.get('tech_skills', []))}
TOOLS        : {', '.join(user_data.get('tools', []))}
COMPETENCIES : {', '.join(user_data.get('soft_skills', []))}

CERTIFICATIONS:
{chr(10).join(user_data.get('certifications', [])) or '(none)'}

WORK EXPERIENCE:
{exp_text or '(none)'}

PROJECTS:
{proj_text or '(none)'}

EDUCATION:
{edu_text or '(none)'}

Output ONLY the LaTeX body (starting from the header \\begin{{center}} block through the last section). No preamble. No \\begin{{document}}."""

    try:
        body = call_llm(system_prompt, user_prompt, temperature=0.2)
        body = clean_latex(body)
        # Assemble: fixed preamble + LLM body + \end{document}
        full_latex = LATEX_PREAMBLE + "\n\n" + body + "\n\n" + LATEX_END
        return {"latex": full_latex}
    except Exception as e:
        return {"error": str(e)}


# ─────────────────────────────────────────────────────────
# AGENT 2 — KEYWORD ANALYZER
# ─────────────────────────────────────────────────────────

def agent_keyword_analyzer(jd_text: str, resume_latex: str) -> dict:
    """
    Compares a job description against the base resume and returns
    a structured ATS keyword gap analysis with score.
    """
    system_prompt = """You are an ATS expert and resume analyst.

Compare the Job Description with the candidate's LaTeX resume.
Return your analysis in EXACTLY this format — no deviations:

## JOB TITLE DETECTED
<exact job title from JD>

## MATCH SCORE
<0-100>%

## MATCHED KEYWORDS
<comma-separated keywords already present in the resume>

## MISSING CRITICAL KEYWORDS
<must-have JD keywords NOT found in the resume>

## MISSING NICE-TO-HAVE KEYWORDS
<secondary/bonus keywords not present>

## SKILLS GAP SUMMARY
<2-3 sentence plain-English summary of the biggest gaps>

## RECOMMENDED CHANGES
- <specific, actionable change to make to the resume>
- <another change>
"""

    user_prompt = f"""JOB DESCRIPTION:
{jd_text}

CANDIDATE'S RESUME (LaTeX):
{resume_latex}

Analyze and return the keyword gap report."""

    try:
        result = call_llm(system_prompt, user_prompt, temperature=0.3)
        return {"raw": result}
    except Exception as e:
        return {"raw": f"Analysis failed: {e}", "error": str(e)}


# ─────────────────────────────────────────────────────────
# AGENT 3 — ATS OPTIMIZER
# Tailors the base resume to a specific JD
# Template structure is LOCKED — only content changes
# ─────────────────────────────────────────────────────────

def agent_ats_optimizer(jd_text: str, base_resume: str, keyword_analysis: str) -> dict:
    """
    Takes the base resume (fixed format) + keyword analysis and returns
    a JD-tailored version in the IDENTICAL LaTeX format.
    Structure, commands, and preamble are untouched.
    """
    system_prompt = r"""You are an expert LaTeX resume writer and ATS optimization specialist.

You receive a candidate's LaTeX resume, a job description, and a keyword analysis.
Return the COMPLETE LaTeX document with content tailored to the JD.

════════════════════════════════════════════════
WHAT YOU MAY CHANGE
════════════════════════════════════════════════
✓ Job title/headline in the header → match JD role title exactly
✓ Summary section → rewrite to lead with JD-relevant skills and keywords
✓ Bullet point wording → weave in MISSING CRITICAL KEYWORDS naturally
✓ Technical Skills section → add missing critical skills if the person actually has them
✓ \textbf{} emphasis → re-bold terms that match JD keywords

════════════════════════════════════════════════
WHAT YOU MUST NEVER CHANGE
════════════════════════════════════════════════
✗ The preamble (\documentclass, \usepackage, \definecolor, \newcommand, etc.)
✗ The custom command names or definitions
✗ Section order or section names
✗ Company names, job dates, degree names, universities, project names
✗ Any facts, metrics, or achievements that are already in the resume
✗ Do NOT fabricate skills, tools, or experience the candidate doesn't have

RULES:
- Return the COMPLETE LaTeX document from \documentclass to \end{document}
- One page only — do not add new sections or excessively lengthen bullets
- Escape all special LaTeX characters properly
- Output ONLY valid LaTeX — no explanations, no markdown, no comments
"""

    user_prompt = f"""JOB DESCRIPTION:
{jd_text}

KEYWORD ANALYSIS (gaps to address):
{keyword_analysis}

BASE RESUME (preserve this exact LaTeX structure — only tailor the content):
{base_resume}

Return the complete ATS-optimized LaTeX document. Start with \\documentclass."""

    try:
        result = call_llm(system_prompt, user_prompt, temperature=0.2)
        return {"latex": clean_latex(result)}
    except Exception as e:
        return {"error": str(e)}